-- MySQL Script generated by MySQL Workbench
-- Thu Dec  2 10:05:28 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_macsz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_macsz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_macsz` DEFAULT CHARACTER SET utf8 ;
USE `db_macsz` ;

-- -----------------------------------------------------
-- Table `db_macsz`.`tblCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_macsz`.`tblCliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `dataNasc` DATE NOT NULL,
  `dataCadastro` DATE NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `senha` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_macsz`.`tblTipoContato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_macsz`.`tblTipoContato` (
  `idTipoContato` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idTipoContato`),
  UNIQUE INDEX `idTipoContato_UNIQUE` (`idTipoContato` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_macsz`.`tblContato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_macsz`.`tblContato` (
  `idContato` INT NOT NULL AUTO_INCREMENT,
  `contato` VARCHAR(254) NOT NULL,
  `idTipoContato` INT NOT NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idContato`),
  UNIQUE INDEX `idContato_UNIQUE` (`idContato` ASC),
  INDEX `fk_tblContato_tblTipoContato_idx` (`idTipoContato` ASC),
  INDEX `fk_tblContato_tblCliente1_idx` (`idCliente` ASC),
  CONSTRAINT `fk_tblContato_tblTipoContato`
    FOREIGN KEY (`idTipoContato`)
    REFERENCES `db_macsz`.`tblTipoContato` (`idTipoContato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblContato_tblCliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `db_macsz`.`tblCliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_macsz`.`tblEndereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_macsz`.`tblEndereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(10) NOT NULL,
  `numero` VARCHAR(5) NOT NULL,
  `complemento` TEXT NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idEndereco`),
  UNIQUE INDEX `idEndereco_UNIQUE` (`idEndereco` ASC),
  INDEX `fk_tblEndereco_tblCliente1_idx` (`idCliente` ASC),
  CONSTRAINT `fk_tblEndereco_tblCliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `db_macsz`.`tblCliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_macsz`.`tblCategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_macsz`.`tblCategoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`idCategoria`),
  UNIQUE INDEX `idCategoria_UNIQUE` (`idCategoria` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_macsz`.`tblProduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_macsz`.`tblProduto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `foto` VARCHAR(255) NOT NULL,
  `preco` VARCHAR(15) NOT NULL,
  `descricao` TEXT NOT NULL,
  `qntde` INT NOT NULL,
  `desconto` INT NOT NULL,
  `idCategoria` INT NOT NULL,
  PRIMARY KEY (`idProduto`),
  UNIQUE INDEX `ididProduto_UNIQUE` (`idProduto` ASC),
  INDEX `fk_tblProduto_tblCategoria1_idx` (`idCategoria` ASC),
  CONSTRAINT `fk_tblProduto_tblCategoria1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `db_macsz`.`tblCategoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_macsz`.`tblPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_macsz`.`tblPedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  UNIQUE INDEX `idClienteProduto_UNIQUE` (`idPedido` ASC),
  INDEX `fk_tblClienteProduto_tblCliente1_idx` (`idCliente` ASC),
  CONSTRAINT `fk_tblClienteProduto_tblCliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `db_macsz`.`tblCliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_macsz`.`tblIngrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_macsz`.`tblIngrediente` (
  `idIngrediente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`idIngrediente`),
  UNIQUE INDEX `idIngredientes_UNIQUE` (`idIngrediente` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_macsz`.`tblProdutoIngrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_macsz`.`tblProdutoIngrediente` (
  `idProdutoIngrediente` INT NOT NULL AUTO_INCREMENT,
  `idIngrediente` INT NOT NULL,
  `idProduto` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`idProdutoIngrediente`),
  UNIQUE INDEX `idProdutoIngrediente_UNIQUE` (`idProdutoIngrediente` ASC),
  INDEX `fk_tblProdutoIngrediente_tblIngrediente1_idx` (`idIngrediente` ASC),
  INDEX `fk_tblProdutoIngrediente_tblProduto1_idx` (`idProduto` ASC),
  CONSTRAINT `fk_tblProdutoIngrediente_tblIngrediente1`
    FOREIGN KEY (`idIngrediente`)
    REFERENCES `db_macsz`.`tblIngrediente` (`idIngrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblProdutoIngrediente_tblProduto1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `db_macsz`.`tblProduto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_macsz`.`tblAdmin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_macsz`.`tblAdmin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `usuario` VARCHAR(254) NOT NULL,
  `senha` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`idAdmin`),
  UNIQUE INDEX `idAdmin_UNIQUE` (`idAdmin` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_macsz`.`tblPedidoProduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_macsz`.`tblPedidoProduto` (
  `idPedidoProduto` INT NOT NULL AUTO_INCREMENT,
  `tblPedido` INT NOT NULL,
  `tblProduto` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`idPedidoProduto`),
  UNIQUE INDEX `idPedidoProduto_UNIQUE` (`idPedidoProduto` ASC),
  INDEX `fk_tblPedidoProduto_tblPedido1_idx` (`tblPedido` ASC),
  INDEX `fk_tblPedidoProduto_tblProduto1_idx` (`tblProduto` ASC),
  CONSTRAINT `fk_tblPedidoProduto_tblPedido1`
    FOREIGN KEY (`tblPedido`)
    REFERENCES `db_macsz`.`tblPedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblPedidoProduto_tblProduto1`
    FOREIGN KEY (`tblProduto`)
    REFERENCES `db_macsz`.`tblProduto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO tblCategoria (nome)
VALUES ('Sabonetes');

INSERT INTO tblProduto (nome, foto, preco, descricao, qntde, desconto, idCategoria)
VALUES ('Perfume', 'Foto do Perfume', 'R$ 30,00', 'Cupcake ipsum dolor sit amet. Candy bear claw liquorice jelly beans lemon drops topping gummies cotton candy. Fruitcake cake cupcake pie gingerbread. Jelly-o apple pie marzipan dragée I love lollipop wafer cookie. I love jelly-o lollipop cookie I love dessert jelly-o candy. Sweet icing chocolate bar I love lemon drops marshmallow chocolate. Topping I love croissant soufflé liquorice. Chocolate cake chocolate sugar plum cake chocolate bar liquorice toffee oat cake. Gummies liquorice icing wafer brownie biscuit biscuit jelly-o. Sweet roll bonbon ice cream candy canes pie macaroon. Toffee lollipop pudding sweet sweet roll candy. Sugar plum lollipop muffin chocolate bar icing I love apple pie.', 5, 0, 1);    

INSERT INTO tblProduto (nome, foto, preco, descricao, qntde, desconto, idCategoria)
VALUES ('Hidratante', 'Foto do Hidratante', 'R$ 16,50', 'Cupcake ipsum dolor sit amet. Candy bear claw liquorice jelly beans lemon drops topping gummies cotton candy. Fruitcake cake cupcake pie gingerbread. Jelly-o apple pie marzipan dragée I love lollipop wafer cookie. I love jelly-o lollipop cookie I love dessert jelly-o candy. Sweet icing chocolate bar I love lemon drops marshmallow chocolate. Topping I love croissant soufflé liquorice. Chocolate cake chocolate sugar plum cake chocolate bar liquorice toffee oat cake. Gummies liquorice icing wafer brownie biscuit biscuit jelly-o. Sweet roll bonbon ice cream candy canes pie macaroon. Toffee lollipop pudding sweet sweet roll candy. Sugar plum lollipop muffin chocolate bar icing I love apple pie.', 8, 0, 2);    

DELETE FROM tblCliente WHERE idCliente = 3;

SELECT * FROM tblCliente;

SELECT * FROM tblProduto;

SELECT * FROM tblCategoria;

desc tblProduto;

desc tblCliente;